### ISSUE TITLE
建议 增强columns定义，区分出列标题和列内容

### ISSUE THREAD

**Issue by kangning1206** [uxcore/uxcore-table#120]
为什么要在定义一列时，分别控制好标题和内容呢？我们在设置列对齐方式时
`align:'right'
`
设置右对其，右对齐一般应用在金额显示，但今天PD说，能否标题仍然靠左或者居中，又想靠左，又想靠右的，无语了，所以今天的需求，是否可以再细化，或者增加一个`contentAlign`属性

**Comment by eternalsky** [comment]
这个需求感觉很没有意义，上下不对齐，会有美的地方吗，能否挑战一下？
