### ISSUE TITLE
支持 matrix

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-table#122]
![Uploading QQ20160407-1.png…](http://gtms02.alicdn.com/tps/i2/TB19p4zMpXXXXXGXFXXgm8WKFXX-707-195.png)

**Comment by eternalsky** [comment]
需要数据结构上的支援

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-matrix matrix 已有，后续需求转移至这里。
