### ISSUE TITLE
uxcore-table列配置项(jsxcolumns) 的type设置select，配置children后，deep-equal页面报Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wushanchao** [uxcore/uxcore-table#135]
和eternalsky讨论过。原因应该是children传入的是react对象，而react对象自带太多属性，导致deep-equal对比不过来。

**Comment by eternalsky** [comment]
后续改为提供 renderChildren 回调来传入 children

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-table/commit/35bf676995917986286dbd9d8472704ea72df8c0
