### ISSUE TITLE
Advanced filter features for particular column data?

### ISSUE THREAD

**Issue by kvetoslavnovak** [uxcore/uxcore-table#142]
Are there any advanced filter features of column data? I cannot see any in the API documentation. 
Filtering features like in http://ant.design/components/table/#components-table-demo-reset-filter which should be based on the same react component.

(Also sorting of data in http://uxco.re/components/table/ examples seems no to work).

**Comment by eternalsky** [comment]
when sort button is clicked, `onOrder` callback will be called if fetchUrl is not defined. `onOrder` description is in [github readme](https://github.com/uxcore/uxcore-table)  now. when fetchUrl is defined, Table will fetch the data via url with specified params (orderColumn & orderType) which can be seen in network panel.

![](https://gw.alicdn.com/tps/TB1ffkpKFXXXXXOXpXXXXXXXXXX-833-598.png)
if these params are not what you want, you can use beforeFetch to adjust them.

filter for the column has not been supported yet, But we have a global search/filter which can be turn on by setting `showSearch` true.

**Comment by kvetoslavnovak** [comment]
Thank you very much. I will try it. 
So it seems that just in the example page http://uxco.re/components/table the sorting and searching/filtering does not work.
