### ISSUE TITLE
左列固定的table， 当没有数据的时候，两边都显示了暂无数据。

### ISSUE THREAD

**Issue by ssehacker** [uxcore/uxcore-table#143]
如题

**Comment by eternalsky** [comment]
目前的实现方式，导致容易出现两个暂无数据，后续改变实现方式后解决此问题。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-table/commit/d75d2c0409dec86b0934235f781d94e344c6fa2f
