### ISSUE TITLE
if data is empty, maybe the table header should set overflow-x auto for show all columns name

### ISSUE THREAD

**Issue by yukap6** [uxcore/uxcore-table#156]
pseudocode may like this:

if(data.length == 0){
  add Class 'data-empty';
}

.data-empty{
    .kuma-uxtable-header-wrapper{
      overflow-x:auto;
      .kuma-uxtable-header-no{
        overflow-x:auto;
      }
    }
  }

**Comment by eternalsky** [comment]
if data is empty, why do you want to check the columns? it seems not helpful.

**Comment by yukap6** [comment]
assume this:
  Table columns is dynamic, every time maybe different, and, the table content data is relation to colums with authority.  As so,  if data is empty, I may check if the colums is out of my authority, then, this will be usefull.

in addition， maybe the component should't decided show or hide the table header, this is task of specific project, and we should't control this?

**Comment by eternalsky** [comment]
@yukap6 only header can scroll looks very weird. when data is empty, Table will render a 'empty data indicator' which should not be scrolled. if you want to check authority, you should check the response of remote request directly.

**Comment by yukap6** [comment]
check the response for developer is ok and not good for normal users.  This is just a case.  On the other hand， even if the data is empty, users should have permission to check all the view, just hidden is't that human friendly.

**Comment by eternalsky** [comment]
@yukap6 we cannot receive the change that only header can be scrolled, more elegant way to resolve your problem is welcomed.
