### ISSUE TITLE
界面中首次加载时，currentPage>1，Pager上位置任然为1

### ISSUE THREAD

**Issue by chrsas** [uxcore/uxcore-table#164]
我是通过jsxData来设置数据，fetchDataOnMount: false，比如
`const jsxdata = {
            currentPage: 4,
            totalCount: 10000,
            data: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
        };`
首次显示的情况就是Pager指向1。

**Comment by eternalsky** [comment]
应该不会存在这个情况的，能否提供一个 demo 来复现你的问题？http://codepen.io/eternalsky/pen/qZwNVL

**Comment by chrsas** [comment]
@eternalsky 这个工具上也能重现，就是不知道怎么搞个链接给你，代码我只好贴在下面了。
`const {
  Table,
} = Uxcore;

class BasicDemo extends React.Component {
    constructor(props){
        super(props);
    }
    render(){
        let columns = [
            { dataKey: 'id', title: 'ID', width: 50,hidden:true},
            { dataKey: 'country', title:'国家', width: 200,ordered:true},
        ];
        const jsxdata = { 
            currentPage: 4, 
            totalCount: 10000, 
            data: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}], 
        };      
        let renderProps={
            height: 200,
            fetchDataOnMount: false,
            jsxcolumns: columns,
            jsxdata,
        };
        return (
            <div>             
                <Table {...renderProps}/>
            </div>
        );
    }
}

ReactDOM.render(
    <BasicDemo />, document.getElementById('container'));`

**Comment by chrsas** [comment]
fetchDataOnMount: true，就正常。

**Comment by eternalsky** [comment]
恩，fetchData 不只是 fetch 远程的，也包括 fetch 本地传来的数据，正常情况下不需要关，不传 url 即可。另外，demo 你只需要 fork 一份，再 save 下来把地址给我就行了。
