### ISSUE TITLE
Table的onPagerChange调用失败

### ISSUE THREAD

**Issue by tootwo2** [uxcore/uxcore-table#165]
我看了Table.jsx。
发现源码591行的fetchLocalData方法中的变量name没有值
”
fetchLocalData(from, props) {
    const me = this;
    if (['pagination', 'order', 'search'].indexOf(from) !== -1) {
      if (name === 'pagination' && props.onPagerChange) {
        props.onPagerChange(me.state.currentPage, me.state.pageSize);
      }
“
其中变量name没有所以始终不会调用onPagerChange。是不是应该给name赋值或者将name替换成from。
PS:我看的demo中的Demo2（GridEditDemo）

**Comment by eternalsky** [comment]
Thanks for reporting bug
