### ISSUE TITLE
麻烦增加行数据滚动入显示区的api

### ISSUE THREAD

**Issue by chrsas** [uxcore/uxcore-table#169]
当一页显示的数据比较多是，不少数据不在显示区，希望能有api将显示区外的数据滚动到显示区内，不改变数据的index

**Comment by eternalsky** [comment]
能说下业务场景吗？没看出来是干什么的，一页数据很多的时候，应该做的是减小分页，而不是通过这些麻烦的方法。

**Comment by chrsas** [comment]
比如一个汽车总成的图片，上面那有很多的配件。这些配件都有热点，在图片边上有一个table用来存放这些热点的信息，在图上了点击一下热点，那么就希望对应的配件信息能滚动到显示区并高亮显示。

**Comment by eternalsky** [comment]
直接把数据换成对应配件的信息不是更直接高效吗？

**Comment by chrsas** [comment]
多谢你的回答，我尝试从其它角度去解决这个问题。
