### ISSUE TITLE
表格支持jsonp, afterFetch ,beforeFetch, processSubdata

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-table#18]
表格支持jsonp跨域请求
数据返回的format
一次请求 ，二级表格的同步数据展示
@majorye @eternalsky

**Comment by eternalsky** [comment]
重新设计后的流程
![sample flowchart template](https://cloud.githubusercontent.com/assets/8038928/9923803/c7344d9c-5d2b-11e5-96dc-855c922a8ead.png)

**Comment by eternalsky** [comment]
关于 jsonp，加入对于 url 解析，以 jsonp 结尾的会自动转为 DataType:jsonp
