### ISSUE TITLE
暂无数据显示了两个图案

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-table#183]
![image](https://cloud.githubusercontent.com/assets/7709602/22054860/e8ccae0c-dd92-11e6-9d2d-99f2db5d9421.png)

我设置了columns中的姓名和工号都是fixed:true，如果表格没有值的时候，左右两边都有暂无数据的提示。。应该只有一个才对

**Comment by eternalsky** [comment]
duplicate https://github.com/uxcore/uxcore-table/issues/143 ，目前业务上可以通过样式覆盖的方式，隐藏这部分。table 组件目前正在改变固定列的实现方式，后面就不会出现类似问题。
