### ISSUE TITLE
行操作之间应该有分隔线隔开的

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-table#190]
现在是这个：
![image](https://cloud.githubusercontent.com/assets/7709602/23780043/43d0214e-057f-11e7-8bce-a9f467a6ee5b.png)

想要的效果是这个
![image](https://cloud.githubusercontent.com/assets/7709602/23780054/55cfae1e-057f-11e7-8ded-34aced3249eb.png)

**Comment by eternalsky** [comment]
这个目前已经 fix
