### ISSUE TITLE
左侧固定列有bug

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-table#191]
![untitled](https://cloud.githubusercontent.com/assets/7709602/23780736/a305f716-0583-11e7-9862-f408359e6502.gif)

**Comment by eternalsky** [comment]
无法复现，能否提供复现步骤及配置。或者提供 codePen demo。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-table/commit/af629fa670f99fd7973b5c4255f73eeeebd784f7

在滚动条始终显示的场合下可以复现。
