### ISSUE TITLE
关于react的版本

### ISSUE THREAD

**Issue by zhurizhe** [uxcore/uxcore-table#193]
注意到uxcore依赖的是react的版本是0.14，如果项目中使用的是0.15，会不会产生冲突？如果会有冲突，有没有什么办法可以解决？

**Comment by eternalsky** [comment]
目前 uxcore 的版本还在兼容 IE8，因此整个环境仍跑在 React 0.14.x 下，从这个月开始，uxcore 开始不再兼容 IE8，关于 React 15.x 的兼容升级也会开始启动。
因为本身需要兼容的点不多，所以如果遇到 React 15.x 相关的兼容问题，也可以提 issue 进行反馈，我们会尽快 fix。

**Comment by zhurizhe** [comment]
好的，非常感谢！
