### ISSUE TITLE
穿入jsxdata重新渲染bug

### ISSUE THREAD

**Issue by 185172970** [uxcore/uxcore-table#195]
在taable.jsx
componentWillReceiveProps(nextProps)方法中

通过deepEqual(nextProps.jsxdata, this.copyData)，判断传入jsxdata与之前是否相等，addValuesInData()引用了copyData导致重新渲染

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-table/commit/d18838faf44cef6542ee38a51097103bd6134c00
