### ISSUE TITLE
rowSelection： false的时候表格样式发生变化， 筛选项宽度被固定，列名称长一点就样式错乱了

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-table#21]
如题。

**Comment by peng2e** [comment]
@majorye  @eternalsky

**Comment by eternalsky** [comment]
rowSelection 和 tree icon 的判断分离，筛选项加入 min-width 去控制最小宽度。

**Comment by eternalsky** [comment]
筛选项宽度不是被固定，而是 list-item 这种 display，默认去读 list 中英文的宽度，如果一个列中只有一个英文词汇，且较短，则会产生比较严重的样式错乱，加入 min-width对这一情况进行控制

**Comment by eternalsky** [comment]
fixed
