### ISSUE TITLE
自定义列的问题

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-table#232]
自定义列中的操作可以被选掉 (dataKey  或者 type 为 `action`)，而且样式好像有问题。

![image](https://user-images.githubusercontent.com/7709602/35084776-8491191c-fc60-11e7-99a1-47003dfb092b.png)

**Comment by eternalsky** [comment]
fix in  https://github.com/uxcore/uxcore-table/commit/34990b3713787ca6fdbd3ed5df2205e2ca87799b
