### ISSUE TITLE
IE11下，table编辑模式的校验有问题

### ISSUE THREAD

**Issue by WisestCoder** [uxcore/uxcore-table#234]
在IE11下， 调用editAllRow钩子后，当新增一行时，会默认进入到列配置的rules中进行校验

**Comment by eternalsky** [comment]
IE11 下有一个 bug 是，input 有 placeholder 的情况下会自动触发一次，onCHange，如果想要避开这个 bug，可以在 IE11 下不要传入 placeholder 来解决。

**Comment by WisestCoder** [comment]
嗯，thanks
