### ISSUE TITLE
addEmptyRow新增行控制插入顺序

### ISSUE THREAD

**Issue by eJayYoung** [uxcore/uxcore-table#236]
RT：
目前新增行，默认是在table的最底下一行插入，但是对于用户体验来说，当table出现滚动条时，每次新增都要自己滚到到最底下，十分不方便，因此产生了新增行在从最上面开始新增的需求，但是现在实现从顶部插入不是很方便，需要自己调用内部的addJSXIdsForRecord方法生成新增行数据，再合并Table的state。

在此想提一个PR的方案：
给[addEmptyRow](https://github.com/uxcore/uxcore-table/blob/74d80f59811db3fa012c78147723cb61de44aac1/src/methods.js#L5)添加一个boolean的参数来控制是否reverse，默认为false
```
function addEmptyRow(cb, reverse = false) {
  this.insertRecords({}, cb, reverse);
}
```
设置为true时，[insertRecords](https://github.com/uxcore/uxcore-table/blob/bdd97bd336e28d2fec6910a3c24ae2372a653c1f/src/innerMethods.js#L66)中
```
function insertRecords(obj, cb, reverse) {
  ...
  const content = !!reverse ? util.mergeData(objAux, me.state.data) : util.mergeData(me.state.data, objAux);
}
```
这样是否可行？

**Comment by eternalsky** [comment]
cb 作为第一个参数，比较怪异，建议新增加新方法，addEmptyRowFromTop(cb) 和 addRowFromTop(data, cb)

**Comment by eternalsky** [comment]
close for https://github.com/uxcore/uxcore-table/pull/237, thanks pr.
