### ISSUE TITLE
表格是否需要支持跨页勾选、是否需要提供获取已勾选数据的api

### ISSUE THREAD

**Issue by WisestCoder** [uxcore/uxcore-table#239]
由于没有提供获取已勾选数据的api，导致每次在切换分页的时候，都要手动去清空selectedRows。

**Comment by eternalsky** [comment]
有 rowSelection 的 onSelect 回调用于告知选中信息，可以记录下来。api 对于 React 组件来说是反模式，正常来说，都应该通过回调来获取。
