### ISSUE TITLE
在开启树形表格的情况下,如果数据内容不满足树形表格格式,会多出来一个具有宽度的空div

### ISSUE THREAD

**Issue by huangweb** [uxcore/uxcore-table#247]
![image](https://user-images.githubusercontent.com/13048763/44126796-bb0693fe-a06c-11e8-8fee-25e8199aa04e.png)
![image](https://user-images.githubusercontent.com/13048763/44126797-bdcf1e4e-a06c-11e8-85b0-dffcd1b345ea.png)

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-table/commit/1dcd1b4a31f3ddaa602a6463ca3a0c09e4e6a2e9
