### ISSUE TITLE
外层通过传入 currentPage 属性无法重置内部的 currentPage 值，有这个机制，但是实现有 bug

### ISSUE THREAD

**Issue by ex90rts** [uxcore/uxcore-table#249]
升级 V16 之前，是因为 componentWillReceiveProps 方法中， fetchData 在 setState 之前调用了，而发起请求里面的 currentPage 参数是从 state 中获取的，导致新传入的 props 值没起作用。

https://github.com/uxcore/uxcore-table/blob/7.x/src/Table.jsx#L125  这里先 fetchData 了
https://github.com/uxcore/uxcore-table/blob/7.x/src/Table.jsx#L511 这里 currentPage 是从当前 state 中读取的

---

升级 V16 之后，是因为 getDerivedStateFromProps 中用来对比的 state.lastCurrentPage 值在内部翻页的时候未去更新，始终是第一次渲染传入的值，而外层一般是重置到第一页，导致 props.currentPage 始终与 state.lastCurrentPage 相等并等于 1。

https://github.com/uxcore/uxcore-table/blob/master/src/Table.jsx#L988  这里应该同时更新 lastCurrentPage

**Comment by eternalsky** [comment]
这里只有props 变化，才可以更新 state，否则内部贮存的 state，在外部刷新后就会强制和外部的props变成一样的了。
