### ISSUE TITLE
支持每个单元格自定义

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-table#30]
加入一个 modifyCell 的 方法，传回 children、rowIndex，colIndex，使用户有机会，对每一个节点进行自定义。

**Comment by majorye** [comment]
use formatHandler to process it, like 

```
let columns = [
           ...
            { dataKey: 'email',title:"Email",width: 200, formatHanlder: function(){
                 return ...
           }}
           ...
        ];
```

  render  & formatHandler relationship 
- in render, we call formatHandler to format render content before render content return

**Comment by majorye** [comment]
which  scenario we need this feature?
1.  cell data , we should process the rowData , then get it
2.  diff role, diff case  , show diff action (for action column)

### certain type column

right now, we have  some type of column:
- action
- checkbox
- select
- text
- person
- money
- card
- cnmobile

the display of these columns have been fixed, so for the custom cell feature, should just for cell data custom. 

### Custom column

for some special requirement , we have custom column way to meet it :  use "render" function to meet it, it has the highest priority between type column . 

like below ,  the Monty column will use custom render way, not the type 'money' way. 

```
      { dataKey: 'email',title:"Money",type:'money',width: 200,ordered:true , render: function(){ ... }}
```

use certain type, but also want custom column , this requirement become invalid, right now do not support .

So for custom cell feature, we could add Hook before render, named "beforeRender" , give the hook for user , have opportunity to custom the cell data

**Comment by eternalsky** [comment]
In fact，`render` has been playing the role of `modifyCell` and has the highest flexibility. At this point, the issue may be meaningless and even `beforeRender` is useless too. Just as you say, if one wants to use certain type and also to modify the cell, using `render`to realize the type by oneself is the best way.
