### ISSUE TITLE
props jsxdata 变化时，grid 不会刷新View

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-table#36]
原因是 props.jsxdata 只在组件初始化时传入过一次，之后 props 更改，不会再去修改 state.data，但不能在 willReceiveProps 的时候调用 fetchData，这样会导致频繁地发 ajax 请求。因此只能单独 set

**Comment by eternalsky** [comment]
Grid 的 edit mode 应该提供一种 reset 机制，使自己内部的值可以被组件外 set

**Comment by majorye** [comment]
fix by @eternalsky  
![image](https://cloud.githubusercontent.com/assets/36510/10681162/0d4b00ac-7959-11e5-9077-a32f2b11efda.png)
