### ISSUE TITLE
左列固定 table 两个问题

### ISSUE THREAD

**Issue by peng2e** [uxcore/uxcore-table#59]
问题1、 没有column 没有 jsxdata的时候，样式是乱的。
问题2、 在左侧固定，table 有横向滚动条的时候， 筛选列的那个按钮不见了

**Comment by eternalsky** [comment]
问题1解决的正确方式应该是

``` javascript
if (state.xxx not empty) {
    return <Table></Table>
}
```

任何一个组件也不能保证在所有参数都不齐全的情况下还能生成正确，所以才有是否必须这一项
