### ISSUE TITLE
table分页bug，删除当前分页的最后一条数据，页面数据显示为空

### ISSUE THREAD

**Issue by robin71** [uxcore/uxcore-table#71]
【操作步骤】：
1、当前有21条数据，将每页显示10条记录，共三页。
2、翻到第三页后，将最后一条数据删除；
【期望结果】：返回到分页的第一页，并且展示第一页的数据
【实际结果】：还是在第三页，且页面显示无数据

**Comment by eternalsky** [comment]
正确的顺序应为：删除最后一条数据后，在 fetchData 时做文章，可以在这时先修改 fetchParams，去 fetch 第一页的数据，此时 table 会根据返回数据的 currentPage 自动调整至第一页。

Table 会增加相应的对返回数据中 currentPage 的处理。
