### ISSUE TITLE
增加setData 接口

### ISSUE THREAD

**Issue by lvon** [uxcore/uxcore-table#90]
能不能增加setData 接口？
有些时候修改一行的数据会影响到别的行，没有这个接口的话需要自己维护数据
这个时候 Table 维护的那份数据就没有意义

**Comment by eternalsky** [comment]
能给出一个具体的场景吗，比如 修改某一行数据，是如何影响其他行的

**Comment by lvon** [comment]
比如 每行都有 money 这一列，总钱数是一定的。
第一行不可编辑，假设是10。 这时候添加第二行 money 是 1 ，要求第一行的 money 变为 9。

还有，双击这个事件没有放出来，现在直接就是双击编辑。如果我不想让某些行被编辑，现在做不到

**Comment by eternalsky** [comment]
@lvon 1.2.3 之后的版本，已经支持关闭双击编辑

**Comment by eternalsky** [comment]
@lvon 这种情况，请使用 Table 的 onChange API，配合同步修改 jsxdata 来完成~

===== edit =====
推荐这种方式，是因为这种方式可能更加通用，如果要是设计 setDate 这样的 api，你期待是怎么使用呢

**Comment by lvon** [comment]
按你的方法试了一下，onChange时的当次修改只会在下一次onChange触发时生效。也可能是我的用法有问题，没有仔细研究，我目前的解决方式是另外维护一份数据。（这个暂时就想这么解决了，毕竟自己维护数据自由度更高）

setData 可以有两种方式：
1.setData(obj)  obj 就是整个table的数据，用户通过getData() 拿到obj之后，可以随便修改（只可以修改值，不能修改数据结构），然后通过setData(obj)，直接替换你维护的table数据。也就是说用户可以通过修改obj达到三个效果，增删改。可能你需要一部分固定的数据，比如：jsxid，你可以定一个规则，这部分你需要的数据让用户按你的规则改。
2.setData(rowData,index) 其实1实现了，这个也就实现了，rowData： 某行对应的数据，index：行的jsxid或者行数。这个接口只是1的升级，让用户更容易实现”改“这个需求。

其中可能会遇到问题，比如：用户非要修改数据结构怎么办？ 这种人可以拉出去斩了。别人要使用你做的插件，就要遵守你定的规则，只要规则定好，我觉得这个接口应该没问题的。

**Comment by eternalsky** [comment]
1的接口方式，这个 setData 其实就和 jsxdata 是一样的了，当 jsxdata 发生改变时，Table 的数据就会随之改变
2的接口方式，感觉比较鸡肋，因为明显1已经实现了，而且灵活性要高很多，之所以用起来你感觉有点问题，可能是因为目前对 jsxdata，内部还没有做 deepcopy 的保护，这导致你在外面使用时需要自己套一层 deepcopy 才可以

**Comment by eternalsky** [comment]
改造后的 jsxdata 可以承载此任务
